### PR TITLE
style: simplify string formatting for readability

### PR DESCRIPTION
**Pull request by hamirmahal**

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
This shouldn't cause any user-facing changes.

The goal here is to improve code readability and maintainability.

**Comment by hirehamir** [comment]
@alokedesai are you open to this change?

**Comment by alokedesai** [comment]
@hamirmahal we aren't accepting contributions to this repo at the moment. I appreciate you trying to improve this but there's meaningful eng cost for us diverging from the upstream repo so I'd only like us to do it when it makes sense / there's a strong use case.

**Comment by hirehamir** [comment]
That makes sense. I appreciate the explanation.

**Pull request closed without merging**
